# Lesson 5 Numpy

## 随堂练习

分别用`arange`和`linspace`在0-10区间内均匀取10个值[0,...,10]

In [ ]:
import numpy as np

# 使用linspace
arr1 = np.linspace(0,10,10)
print('np.linspace的结果是:{}'.format(arr1))

# 使用arange
step = 10 / 9  
arr2 = np.arange(0,10.001,step)
print('np.arange的结果是:{}'.format(arr2))

np.linspace的结果是:[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
np.arange的结果是:[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


## 随堂练习：生成矩阵

In [ ]:
# 直接生成
import numpy as np
n = 5
m = np.ones([n,n])
for i in range(n):
    m[i,:] = i

print(m)
print(m.T)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [5]:
# 数组合并法
import numpy as np

a = np.ones(5)
b = np.vstack((a * 0, a * 1,a * 2, a* 3, a * 4))
print(b)
print(b.T)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [3]:
# 这里有一个更加巧妙地方式：运用repeat
a = np.arange(5)
m = a.repeat(5,axis=0).reshape(5,-1)
print(m)
print(m.T)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
# 或者使用list的单纯复制功能
import numpy as np
a = list(range(5))
a = np.array(a * 5).reshape(5,-1)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


> 从这些中我们可以看到列表的乘法（`*`）几乎等价于数组的复制（`repeat`），同时要注意`repeat`的`axis`问题

In [11]:
import numpy as np
a = np.zeros(5)
b = np.ones(5)
c = b * 2
d = b * 3
e = b * 4
print(np.vstack((a,b,c,d,e)))

print(np.c_[a,b,c,d,e])

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 还有一种方法就是直接np.arange(25)然后整除或者取余

数据保存

In [1]:
import numpy as np
x = y = z = np.arange(0.0,5.0,0.5)
np.savetxt('D:\\my study\\Python Study\\Lesson\\test_5.out',x,delimiter=',')

np.savetxt('D:\\my study\\Python Study\\Lesson\\test1_5.out',(x,y,z))

np.savetxt('D:\\my study\\Python Study\\Lesson\\test2_5.out',x,fmt='%6.4f')

## 随堂练习

生成如下矩阵并保存到文件 matrix.txt 中

[[1,2,3,4,5],

[6,7,8,9,10],

[11,12,13,14,15],

[16,17,18,19,20],

[21,22,23,24,25]]

从文件中读取矩阵，前三列加5，后两列加10，保存到新文件matrix_new.txt 中

In [6]:
import numpy as np
filename = "D:\\my study\\Python Study\\Lesson\\matrix.txt"

m = np.arange(1,26).reshape(5,-1)
np.savetxt(filename,m)

In [10]:
filename_new = 'D:\\my study\\Python Study\\Lesson\\matrix_new.txt'
data = np.loadtxt(filename)
data[:,:3] = data[:,:3] + 5
data[:,-2:] = data[:,-2:] + 10
np.savetxt(filename_new,data)

| 项目        |          range  |               np.arange | np.linspace           |
| --------- | ----------------------: | ----------------------: | --------------------- |
| 返回类型      |          `range` 对象 |               `ndarray` | `ndarray`             |
| 是否包含 stop |                       否 |                  否 | 是 |
| 参数方式      | start, stop, step（均需为整数） | start, stop, step（支持浮点） | start, stop, num（点数）  |
| 精度（浮点）    |                N/A（只整数） |                浮点易有累计误差 | 通过等分计算更可靠             |
| 内存占用      |                   低（惰性） |                高（一次性数组） | 高（一次性数组）              |
| 适用场景      |                控制流、循环索引 |    数值向量化（当步长为整数或精度要求不高） | 绘图、等分区间、需要精确点数        |
| 推荐        |                    遍历索引 |            快速生成数组（注意浮点） | 需要精确数量或包含终点时          |


| 函数              | start 是否默认 | step 是否默认 | stop 是否默认 | 是否能只写一个参数  |
| --------------- | ---------- | --------- | --------- | ---------- |
| **range**       | 默认 0       | 默认 1      | ❌ 必须给     | ✔（表示 stop） |
| **np.arange**   | 默认 0       | 默认 1      | ❌ 必须给     | ✔（表示 stop） |
| **np.linspace** | ❌ 没默认      | ❌ 没默认     | ❌ 必须给     | ❌（不能只写一个）  |
